### ISSUE TITLE
premake4 failed on Linux

### ISSUE THREAD

**Issue by Mailaender** [unknownworlds/decoda#17]
```
premake4.lua:9: attempt to call global 'vpaths' (a nil value)
```

using http://software.opensuse.org/package/premake4

and 

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

**Comment by benoit-germain** [comment]
I had the same issue on windows until I used premake 4.4 beta 4. Looks like `vpaths` is a late addition.

**Comment by Mailaender** [comment]
Update to https://build.opensuse.org/request/show/205790 fixed it.

**Comment by Mailaender** [comment]
However still fails #18 probably because of missing dependencies or Windows-only support.
